eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: http://localhost:9094
          predicates:
            - Path=/users/**
        - id: rideservice
          uri: http://localhost:9095
          predicates:
            - Path=/ride/**
        - id: driverservice
          uri: http://localhost:9096
          predicates:
            - Path=/drivers/**
        - id: paymentservice
          uri: http://localhost:9097
          predicates:
            - Path=/payments/**
